# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'profileUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # For Utils
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'FloatingPanel'
  pod 'lottie-ios'
  pod 'StepSlider'
  
  # For Rx
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxGesture'

  # For Firebase
  pod 'FirebaseAuth'
  
  # Pods for profileUI

  target 'profileUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'profileUIUITests' do
    # Pods for testing
  end

end
