# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Fintech' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fintech
  # Package for Rx
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxGesture'
  
  # Package for Firebase
  pod 'FirebaseCore'
  pod 'FirebaseFirestore'
  pod 'FirebaseAuth'
  pod 'FirebaseStorage'

  target 'FintechTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FintechUITests' do
    # Pods for testing
  end

end
