# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'Attendance' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Attendance
  
  # package for firebase
  pod 'FirebaseCore'
  pod 'FirebaseFirestore'
  pod 'FirebaseAuth'
  pod 'FirebaseStorage'
  
  # package for util
  pod 'SnapKit'
  pod 'Kingfisher'
  
  # package for custom class
  pod 'DropDown'
  pod 'lottie-ios'
  pod 'ReachabilitySwift'
  pod 'FloatingPanel'
  
  # package RX
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxGesture'
  
  # package debugging
  pod 'netfox', :configurations => 'Debug'

  target 'AttendanceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AttendanceUITests' do
    # Pods for testing
  end

end
