# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'Attendance' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Attendance
  pod 'FirebaseCore'
  pod 'FirebaseFirestore'
  pod 'FirebaseAuth'
  pod 'FirebaseStorage'
  pod 'lottie-ios'
  pod 'SnapKit'
  pod 'DropDown'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Kingfisher'

  target 'AttendanceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AttendanceUITests' do
    # Pods for testing
  end

end
