# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Profile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'StepSlider'

  # Pods for Profile

  target 'ProfileTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProfileUITests' do
    # Pods for testing
  end

end
