# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'profileUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'SHSearchBar'
  pod 'RxSwift'
  pod 'RxCocoa'
  
  # Pods for profileUI

  target 'profileUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'profileUIUITests' do
    # Pods for testing
  end

end
